### ISSUE TITLE
Getting a 401 UnAuthorized Exception while using the REST Api

### ISSUE THREAD

**Issue by h4ck3r8ug5** [ninjakitteh69/Clickatell-Csharp#1]
Hi there.

While trying to send a test sms using the REST Api, I am getting the following error: Error occured during Clickatell Authenticate. Details: The remote server returned an error: (401) Unauthorized.

I have used the correct Api Key from the SMS integrations and using the C# clickatell library, I get the above error.

I renewed my Api key as well and still, the same error.

My Code:

![capture](https://cloud.githubusercontent.com/assets/2481409/23605573/f1795c60-0265-11e7-95d6-4446e18d0169.PNG)

Any ideas?
Charles

**Comment by ninjakitteh69** [comment]
Hi h4ck3r8ug5,
Are you using a SMS Platform or a Communicator / Central Account?
Then are you using an HTTP API ID or a REST API ID?

**Comment by ninjakitteh69** [comment]
This issue was fixed in Release 2.0.1
Please re-open if issue persists
